import './js/gotop'
import './js/burger-menu'
import './js/modal-buy-now'
import './js/video-player'
import './js/slider-choco'
import './js/slider-reviews'
import './js/modal-leave-review'
import './js/modal-explore-chocolate'